### ISSUE TITLE
Веб-дизайн приложения

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar#1]
### User stories
- Я, как владелец продукта, хочу чтобы приложение соответсвовало принятой стилистике заказчика
- Я, как пользователь, хочу чтобы я мог пользоваться приложением на ПК

  - [ ]  https://github.com/IT-Prospects/business-calendar-frontend/issues/4
  - [ ]  https://github.com/IT-Prospects/business-calendar-frontend/issues/6
  - [ ]  https://github.com/IT-Prospects/business-calendar-frontend/issues/5

- Я, как пользователь, хочу чтобы я могу пользоваться приложением на телефоне
